server:
  port: 8080

spring:
  application:
    name: cliente

  datasource:
    username: 'financeira'
    password: '123456'
    url: jdbc:postgresql://localhost:5432/clientes

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'


    hibernate:
      ddl-auto: 'create-drop'
    show_sql: 'true'